nginx:
  build: nginx/
  links:
    - webapp1
    - webapp2
  ports:
   - "80:80"

webapp1:
  build: .
  hostname: webapp1
  links:
    - redis
  ports:
    - "8081:8080"

webapp2:
  build: .
  hostname: webapp2
  links:
    - redis
  ports:
    - "8082:8080"

redis:
  image: redis
  hostname: redis
  ports:
    - "6379:6379"